TASK_STATUS_CREATED = "CREATED"
TASK_STATUS_WAITING_USER_INPUT = "WAITING_USER_INPUT"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
TASK_STATUS_FAILED = "FAILED"

TASK_PHASE_REQUIREMENT_ANALYZING = "REQUIREMENT_ANALYZING"
TASK_PHASE_TASK_DECOMPOSING = "TASK_DECOMPOSING"
TASK_PHASE_TASK_EVALUATING = "TASK_EVALUATING"
TASK_PHASE_SUBTASK_RUNNING = "SUBTASK_RUNNING"
TASK_PHASE_REPORTING = "REPORTING"
TASK_PHASE_DONE = "DONE"

SUBTASK_STATUS_PENDING = "PENDING"
SUBTASK_STATUS_READY = "READY"
SUBTASK_STATUS_RUNNING = "RUNNING"
SUBTASK_STATUS_RETRY_PENDING = "RETRY_PENDING"
SUBTASK_STATUS_COMPLETED = "COMPLETED"
SUBTASK_STATUS_NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"
SUBTASK_STATUS_BLOCKED_BY_DEPENDENCY = "BLOCKED_BY_DEPENDENCY"

# Terminal subtask statuses (no further processing)
SUBTASK_TERMINAL_STATUSES = frozenset([
    SUBTASK_STATUS_COMPLETED,
    SUBTASK_STATUS_NEEDS_HUMAN_REVIEW,
    SUBTASK_STATUS_BLOCKED_BY_DEPENDENCY,
])

